export const GET_COURSES = "GET_COURSES";
export const GET_COURSE = "GET_COURSE";
export const COURSE_REQUEST = "COURSE_REQUEST";
export const COURSE_SUCCESS = "COURSE_SUCCESS";
export const COURSE_ERROR = "COURSE_ERROR";
